version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: reservasapp-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reservas_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d  # ejecuta 01_, 02_, 03_... la PRIMERA vez